config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/friends", to: "friends#index", as: "friends_index"
  resources :friends

  get "/articles", to: "articles#index", as: "articles_index"
  resources :articles do
    resources :comments
  end

  get "/home/about", to: "home#about", as: "about" # Rota para a página "Sobre"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible

    has_many :comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    VALID_STATUSES = ['public', 'private', 'archived']

    validates :status, inclusion: { in: VALID_STATUSES }

    def archived?
        status == 'archived'
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

  def archived?
    status == 'archived'
  end
end

app/models/concerns/visible.rb
module Visible

    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']

    included do
        validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
          where(status: 'public').count
        end
    end

    def archived?
      status == 'archived'
    end
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy


    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end

    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article), status: :see_other
    end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :social_media, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%# #243441 %>
<div class="card">
  <div class="card-body">
<%= form_with model: article do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %><br>
    <%= form.text_field :title,  class: "form-control" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class="form-text"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %><br>
    <%= form.text_area :body,  class: "form-control" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div class="form-text"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :status, class: "form-label" %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public', class: "form-select" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div class="d-flex justify-content-between">
<div> Our blog has <%= Article.public_count %> articles and counting! </div>
<%= link_to "New Article", new_article_path, class: "btn btn-primary" %>
</div>
<div>
		<ul class="list-group mt-3 text-white">
        <% @articles.each do |article| %>
    	<% unless article.archived? %>
		  <li class="list-group-item d-flex justify-content-between align-content-center">
		  	<div class="d-flex flex-row">
		  		<div class="ml-2">
		  			<h6 class="mb-0"><%= link_to article.title, article %></h6>
		  			<div class="about">
		  				<%# <span>22 Files</span> colocar tamanho do texto%>
		  				<%# <span>Jan 21, 2020</span> colocar data %>
		  			</div>
		  		</div>
				<div>
					<tr>
    					<td><%= link_to 'Show', article_path(article) %></td>
    					<td><%= link_to 'Edit', edit_article_path(article) %></td>
    					<td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  					</tr>
				</div>
		  	</div>
		  </li>
        <% end %>
  		<% end %>
    </ul>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

       <div class="row">
    <div class="col text-center">
<%= link_to "Back", :back, class: 'btn btn-secondary' %>
</div>
</div>

app/views/articles/show.html.erb
<div class="card">
  <div class="card-header">
    <div style="display: flex;">
      <h1><%= @article.title %></h1>
      <div style="display: flex;">
        <span><%= link_to "Edit", edit_article_path(@article) %></span>
        <span><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></span>
      </div>
    </div>
  </div>

  <div class="card-body">
    <p><%= @article.body %></p>

    <div style="display: flex;">
    <p class="d-inline-flex gap-1">
  <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Comments
  </a>
</p>

    </div>
  </div>

<div class="card-footer">
  <div class="collapse" id="collapseExample">
  <div class="card card-body">
    <ul class="list-group">
    <%= render @article.comments %>
    </ul>
  </div>
</div>
</div>
</div>


  <div class="card card-body">
    <h4>Add a comment:</h4>
<%= render 'comments/form' %>
  </div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <li class="list-group-item">
    <div>
      <span> <strong><%= comment.commenter %>:</strong> <%= comment.body %> </span>
      <span class="btn">
  <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
          } 
  %>
</span>
    </div>
  </li>

<% else %>
<p>No comments yet!</p>
<%end%>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
   <div class="field form-group">
    <%= form.label :commenter %><br />
    <%= form.text_field :commenter, autofocus: true, autocomplete: "commenter", class:'field form-control', placeholder: 'Commenter' %>
  </div>

   <div class="field form-group">

    <%= form.label :body %><br>
    <%= form.text_area :body ,  class:'field form-control', placeholder: 'Content'%>
   </div>

    <div class="field form-group">
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
   </div>

  <div class="actions mt-3">
             <div class="row">
    <div class="col text-center">
    <%= form.submit%>
   </div>
   </div>
   </div>

<% end %>

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :social_media, class:"form-control", placeholder:"Social Media" %>
  </div>
  <div class="field form-group">
    
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  
<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Social media:</strong>
    <%= friend.social_media %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>

<br/>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %>

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Social M</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td>
<%= link_to friend.first_name + ' ' + friend.last_name, friend %>
          </td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.social_media %></td>
          
          
          
          
          
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<% else %>

<h1>Hello World!</h1>
This is my first Rails Webpage...

<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path , class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  | 
    <%= @friend.phone %>  |  
    <%= @friend.social_media %>

  </p>
  <br/>

  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
   
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

</div>

app/views/home/about.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-5">
  <%# #c52f29 %>
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
              <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
    

            <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Articles", articles_index_path, class:"nav-link" %>
        </li>

            <li class="nav-item">
          <%= link_to "Friends", friends_index_path, class:"nav-link" %>
        </li>
        <%end%>

                    <li class="nav-item">
              <%= link_to "About", about_path, class:"nav-link" %>
        </li>
      </ul>


      <ul class="d-flex navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
      <%= render 'layouts/header' %>

    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
      <%= yield %>
    </div>

      <%= render 'layouts/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>